export default {
    title: 'Entur SDK',
    description: 'Docs for the Entur JavaScript SDK',
    files: './docs/**/*.mdx',
    menu: [
        'Entur SDK',
        'Getting Started',
        'Geocoder',
        'NSR',
        'Travel',
        'Departures',
        'Places',
        'Mobility',
        'Bikes',
        'Scooters',
        'Utils',
        'Advanced',
    ],
    typescript: true,
}
