export enum TransportMode {
    AIR = 'air',
    BUS = 'bus',
    CABLEWAY = 'cableway',
    CAR = 'car',
    COACH = 'coach',
    FUNICULAR = 'funicular',
    LIFT = 'lift',
    METRO = 'metro',
    RAIL = 'rail',
    TRAM = 'tram',
    WATER = 'water',
}

export enum TransportSubmode {
    AIRPORT_LINK_BUS = 'airportLinkBus',
    AIRPORT_LINK_RAIL = 'airportLinkRail',
    CITY_TRAM = 'cityTram',
    DOMESTIC_FLIGHT = 'domesticFlight',
    EXPRESS_BUS = 'expressBus',
    FUNICULAR = 'funicular',
    HELICOPTER_SERVICE = 'helicopterService',
    HIGH_SPEED_PASSENGER_SERVICE = 'highSpeedPassengerService',
    HIGH_SPEED_VEHICLE_SERVICE = 'highSpeedVehicleService',
    INTERNATIONAL = 'international',
    INTERNATIONAL_CAR_FERRY = 'internationalCarFerry',
    INTERNATIONAL_COACH = 'internationalCoach',
    INTERNATIONAL_FLIGHT = 'internationalFlight',
    INTERNATIONAL_PASSENGER_FERRY = 'internationalPassengerFerry',
    INTERREGIONAL_RAIL = 'interregionalRail',
    LOCAL = 'local',
    LOCAL_BUS = 'localBus',
    LOCAL_CAR_FERRY = 'localCarFerry',
    LOCAL_PASSENGER_FERRY = 'localPassengerFerry',
    LOCAL_TRAM = 'localTram',
    LONG_DISTANCE = 'longDistance',
    METRO = 'metro',
    NATIONAL_CAR_FERRY = 'nationalCarFerry',
    NATIONAL_COACH = 'nationalCoach',
    NIGHT_BUS = 'nightBus',
    NIGHT_RAIL = 'nightRail',
    RAIL_REPLACEMENT_BUS = 'railReplacementBus',
    REGIONAL_BUS = 'regionalBus',
    REGIONAL_CAR_FERRY = 'regionalCarFerry',
    REGIONAL_RAIL = 'regionalRail',
    SCHOOL_BUS = 'schoolBus',
    SHUTTLE_BUS = 'shuttleBus',
    SIGHTSEEING_BUS = 'sightseeingBus',
    SIGHTSEEING_SERVICE = 'sightseeingService',
    TELECABIN = 'telecabin',
    TOURIST_RAILWAY = 'touristRailway',
}

export enum LegMode {
    AIR = 'air',
    BICYCLE = 'bicycle',
    BUS = 'bus',
    CABLEWAY = 'cableway',
    CAR = 'car',
    COACH = 'coach',
    FOOT = 'foot',
    FUNICULAR = 'funicular',
    LIFT = 'lift',
    METRO = 'metro',
    RAIL = 'rail',
    TRAM = 'tram',
    WATER = 'water',
}

/**
 * All valid values for the "mode" parameter to JourneyPlanner
 */
export enum QueryMode {
    AIR = 'air',
    BICYCLE = 'bicycle',
    BUS = 'bus',
    CABLEWAY = 'cableway',
    CAR = 'car',
    CAR_DROPOFF = 'car_dropoff',
    CAR_PARK = 'car_park',
    CAR_PICKUP = 'car_pickup',
    COACH = 'coach',
    FOOT = 'foot',
    FUNICULAR = 'funicular',
    LIFT = 'lift',
    METRO = 'metro',
    RAIL = 'rail',
    TRAM = 'tram',
    TRANSIT = 'transit',
    WATER = 'water',
}
